### ISSUE TITLE
Bone name truncated

### ISSUE THREAD

**Issue by TempContainer** [Shadowth117/Aqua-Toolset#13]
I use this tool to unpack `c5100.chrbnd.dcx` (Guardian Ape from Sekiro) into `fbx` format. When I import it into DCC software like Blender, I find that some bone names are truncated, which causes mojibake when the bone names are in Japanese. I don't know whether this result is intentional. When importing the model into UE will occur errors, and it may causes skinning issues with the imported animations (I'm not certain, but have encounted that).

**Comment by Shadowth117** [comment]
PSO2 had a limit of 0x20 characters per bone name essentially. Probably should have had some kind of handler for that like I do for other strings, but I just never did it for bones I guess. I'll go and add it.

**Comment by Shadowth117** [comment]
Latest release should handle this appropriately. Enjoy!
