### ISSUE TITLE
CMX Patcher results in NGS Benchmark to have corrupt faces

### ISSUE THREAD

**Issue by Arlisbloxer05** [Shadowth117/Aqua-Toolset#14]
![image](https://github.com/user-attachments/assets/d54878ed-5ece-4720-b68b-1b27eed6a229)

The latest update to the CMX Patcher (and maybe also NGS, idk, not an expert) seems to result in corrupted faces for the benchmark. And its not just a few, its EVERY face type.

**Comment by NakukotoHoshizora** [comment]
This problem (to varying degrees of cringe) appeared in all face types after the update (this look... she asks to kill her quickly and save her from suffering...)
![Снимок экрана 2024-10-04 211537](https://github.com/user-attachments/assets/36ea7e01-25b7-403a-ad55-f6aa81b7f3c7)

**Comment by Arlisbloxer05** [comment]
I wonder if this happened because of the new Animatica Face's rigging

**Comment by NakukotoHoshizora** [comment]
I think so too. Well, the number of slots for accessories has also changed, and something else in the code related to them (at least that's what the mods developers say)

**Comment by Arlisbloxer05** [comment]
Not sure why they'd need to increase the slots count, you'd still hit cost limit before managing to hit slot limit

**Comment by NakukotoHoshizora** [comment]
Well... if it's a benchmark then you don't have to worry about the cost

**Comment by NakukotoHoshizora** [comment]
By the way, it seems that the old type male face (the very first option) works fine (but only this one)

**Comment by Shadowth117** [comment]
Resolved in this commit: https://github.com/Shadowth117/Aqua-Toolset/commit/6b25b7cbc1dab2b80db6612b505b53d854b8cde8

Really had nothing to do with rigging or any of that. Have a nice day.
