### ISSUE TITLE
Issue when extracting

### ISSUE THREAD

**Issue by audi4444player** [Shadowth117/Aqua-Toolset#7]
Hello, I've never seen this happen before, so I wanted to ask if it's a problem, I get the following error when extracting 
! my pc structure/Desktop/AquaToolset.7z: Unknown method in net6.0-windows\runtimes\linux-arm64\native\libprs_rs.so
! my pc structure/Desktop\AquaToolset.7z: Unknown method in net6.0-windows\runtimes\osx-arm64\native\libprs_rs.dylib
! my pc structure/Desktop\AquaToolset.7z: Unknown method in net6.0-windows\runtimes\win-arm64\native\prs_rs.dll
I'm running windows intel 64 so is this not an issue? I tried redownloading but the same thing.

**Comment by Shadowth117** [comment]
Hi, yeah, please update your 7zip/Winrar. At some point they messed with the 7z formatting and this started happening a few years ago.
