### ISSUE TITLE
UVs from flver is not working

### ISSUE THREAD

**Issue by Eraea** [Shadowth117/Aqua-Toolset#8]
Hi! I used the tool to unpack some flvers from an old PS3 game called ACE:R and the models are all fine but the UVs dont work. Is there any workaround to this?
![image_2024-07-21_225652971](https://github.com/user-attachments/assets/496fc565-1f94-4b8e-bff0-1c072a4af8c1)

**Comment by Shadowth117** [comment]
This may work better for the moment as there's some oddities with the older fromsoft models. Eventually I would like to integrate them properly with modern soulsformats, but for now, you can use this:
https://github.com/WarpZephyr/MassConvertFromModel

**Comment by Shadowth117** [comment]
Was able to check into it. Seems like the current version does work with it so closing this for now.
